[".config/zsh/zsh-autocomplete"]
type = "archive"
url = "https://github.com/marlonrichert/zsh-autocomplete/archive/main.tar.gz"
exact = true
stripComponents = 1

[".config/zsh/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1

[".tmux/plugins/tmux"]
type = "archive"
url = "https://github.com/dracula/tmux/archive/master.tar.gz"
exact = true
stripComponents = 1

[".tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
exact = true
stripComponents = 1

[".config/zsh/zsh-autosuggestions.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/master/zsh-autosuggestions.zsh"
exact = true

[".aliases.d/golang.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/golang/golang.plugin.zsh"
exact = true

[".aliases.d/systemd.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/systemd/systemd.plugin.zsh"
exact = true

[".aliases.d/git.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git/git.plugin.zsh"
exact = true

[".aliases.d/kubectl.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/kubectl/kubectl.plugin.zsh"
exact = true

[".aliases.d/systemadmin.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/systemadmin/systemadmin.plugin.zsh"
exact = true

