#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "SpaceVim"
colorscheme_bg = "dark"
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
default_indent = 4
expand_tab = true
autocomplete_method = "coc"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "fzf"

[[layers]]
name = "tools"

[[layers]]
name = "lang#python"

[[layers]]
name = "lsp"
filetypes = [
	"go",
	"python",
	"c",
	"cpp"
]
enabled_clients = ['pyright']

#run :GoInstallBinaries inside vim
[[layers]]
name = "lang#go"

[[layers]]
name = "git"

[[layers]]
name = 'VersionControl'

[[layers]]
name = "checkers"

[[layers]]
name = "debug"

[[layers]]
name = "lang#sh"

# clang
[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[custom_plugins]]
	repo = 'wakatime/vim-wakatime'
