#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
# colorscheme = "gruvbox"
# colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "nil"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_filetree_gitstatus = true
default_indent = 4
expand_tab = true
colorscheme = "dracula"
colorscheme_bg = "dark"
enable_statusline_mode = true
statusline_left_sections = [
   'winnr',
   'major mode',
   'filename',
   'fileformat',
   'minor mode lighters',
   'version control info',
   'search status'
]
statusline_right_sections = [
   'cursorpos',
   'percentage',
   'input method',
   'date',
   'time'
]


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "fzf"

[[layers]]
name = "tools"

[[custom_plugins]]
repo = "dracula/vim"
name = "dracula"

[[custom_plugins]]
repo = "voldikss/vim-floaterm"
name = "floaterm"

[[custom_plugins]]
repo = "christoomey/vim-tmux-navigator"
name = "vim-tmux-navigator"

[[layers]]
name = "lang#javascript"
format_on_save = true

[[layers]]
name = "lang#python"
format_on_save = true

[[layers]]
name = "lsp"

[[layers]]
name = "lang#go"

[[layers]]
name = "git"

[[layers]]
name = "checkers"

[[layers]]
name = "debug"

[[layers]]
name = "lang#sh"

[[layers]]
name = "sudo"
